# Generated by Django 5.0.1 on 2024-01-20 07:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardsRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
                ('Machine_Id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=True, max_length=200), size=None)),
                ('Name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=True, max_length=200), size=None)),
                ('Value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=True, max_length=200), size=None)),
                ('Title', models.CharField(default=True, max_length=200)),
                ('Mode', models.CharField(default=True, max_length=200)),
            ],
            options={
                'db_table': 'Machines_Schema"."CardsRawData',
            },
        ),
        migrations.CreateModel(
            name='MachineRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Db_Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Timestamp', models.DateTimeField()),
                ('Machine_Id', models.CharField(max_length=150)),
                ('Machine_Location', models.CharField(max_length=250)),
                ('Digital_Input', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
                ('Digital_Output', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
                ('Analog_Input', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), size=None)),
                ('Analog_Output', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), size=None)),
                ('Other', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=True, max_length=100), size=None)),
            ],
            options={
                'db_table': 'Machines_Schema"."MachineRawData',
            },
        ),
    ]
