# Generated by Django 5.0.1 on 2024-01-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsrawdata',
            name='Mode',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cardsrawdata',
            name='Title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
