# Generated by Django 5.0.1 on 2024-01-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nested_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Node_Id', models.IntegerField()),
                ('Node_Left', models.IntegerField()),
                ('Node_Right', models.IntegerField()),
                ('Property', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Users_Schema"."Nested_Table',
            },
        ),
    ]
