# Generated by Django 5.0.1 on 2024-01-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0003_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinedetails',
            name='Manuals',
        ),
        migrations.RemoveField(
            model_name='machinedetails',
            name='Technical_Details',
        ),
        migrations.AddField(
            model_name='machinedetails',
            name='Manuals',
            field=models.ManyToManyField(blank=True, null=True, to='Atoms_users.manuals'),
        ),
        migrations.AddField(
            model_name='machinedetails',
            name='Technical_Details',
            field=models.ManyToManyField(blank=True, null=True, to='Atoms_users.technicaldetails'),
        ),
    ]
