# Generated by Django 5.0.1 on 2024-01-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0004_remove_machinedetails_manuals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iolist',
            name='machine_id',
        ),
        migrations.AddField(
            model_name='iolist',
            name='IO_Group',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinedetails',
            name='IO_Group_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Atoms_users.iolist'),
        ),
    ]
