# Generated by Django 5.0.1 on 2024-01-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0005_remove_iolist_machine_id_iolist_io_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedetails',
            name='Manuals',
            field=models.ManyToManyField(blank=True, to='Atoms_users.manuals'),
        ),
        migrations.AlterField(
            model_name='machinedetails',
            name='Technical_Details',
            field=models.ManyToManyField(blank=True, to='Atoms_users.technicaldetails'),
        ),
    ]
