# Generated by Django 5.0.1 on 2024-01-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0007_machinecardslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinedetails',
            name='IO_Group_Id',
        ),
    ]
