# Generated by Django 5.0.1 on 2024-01-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0008_remove_machinedetails_io_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedetails',
            name='IO_Group_Id',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
