# Generated by Django 5.0.1 on 2024-01-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0009_machinedetails_io_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedetails',
            name='Machine_id',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
