# Generated by Django 5.0.1 on 2024-01-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0010_alter_machinedetails_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinecardslist',
            name='Title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
