# Generated by Django 5.0.1 on 2024-01-30 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0011_machinecardslist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinecardslist',
            name='Card_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Atoms_users.cardinventory'),
        ),
    ]
