# Generated by Django 5.0.1 on 2024-01-30 11:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0012_machinecardslist_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinecardslist',
            name='Unit',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None),
        ),
    ]
