# Generated by Django 5.0.1 on 2024-02-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0013_machinecardslist_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinecardslist',
            name='Conversion_Fun',
        ),
    ]
