# Generated by Django 5.0.1 on 2024-02-02 06:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0014_remove_machinecardslist_conversion_fun'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinecardslist',
            name='Conversion_Fun',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
