# Generated by Django 5.0.1 on 2024-02-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0015_machinecardslist_conversion_fun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinecardslist',
            name='mode',
        ),
    ]
