# Generated by Django 5.0.1 on 2024-02-08 06:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0016_remove_machinecardslist_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinecardslist',
            name='mode',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
