# Generated by Django 5.0.1 on 2024-02-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0017_machinecardslist_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
