# Generated by Django 4.2.10 on 2024-04-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0018_alter_layers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolist',
            name='alarm',
            field=models.BooleanField(default=False),
        ),
    ]
