# Generated by Django 4.2.10 on 2024-05-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atoms_users', '0019_iolist_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(blank=True, max_length=100)),
                ('TimeStamp', models.DateTimeField()),
                ('Message', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'Users_Schema"."Alarm_data',
            },
        ),
    ]
